//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sapService.ConsumerElectric {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transport/", ConfigurationName="ConsumerElectric.ServiceDelegate")]
    public interface ServiceDelegate {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.GetStockResponse GetStock(sapService.ConsumerElectric.GetStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.GetStockResponse> GetStockAsync(sapService.ConsumerElectric.GetStockRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.transportResponse transport(sapService.ConsumerElectric.transportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.transportResponse> transportAsync(sapService.ConsumerElectric.transportRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.t_transResponse t_trans(sapService.ConsumerElectric.t_transRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.t_transResponse> t_transAsync(sapService.ConsumerElectric.t_transRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.ch_transdateResponse ch_transdate(sapService.ConsumerElectric.ch_transdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.ch_transdateResponse> ch_transdateAsync(sapService.ConsumerElectric.ch_transdateRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.ch_transtypeResponse ch_transtype(sapService.ConsumerElectric.ch_transtypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.ch_transtypeResponse> ch_transtypeAsync(sapService.ConsumerElectric.ch_transtypeRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.GetjdstoretoshopResponse Getjdstoretoshop(sapService.ConsumerElectric.GetjdstoretoshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.GetjdstoretoshopResponse> GetjdstoretoshopAsync(sapService.ConsumerElectric.GetjdstoretoshopRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.GetfxxtoshopResponse Getfxxtoshop(sapService.ConsumerElectric.GetfxxtoshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.GetfxxtoshopResponse> GetfxxtoshopAsync(sapService.ConsumerElectric.GetfxxtoshopRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.testResponse test(sapService.ConsumerElectric.testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.testResponse> testAsync(sapService.ConsumerElectric.testRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sapService.ConsumerElectric.testQResponse testQ(sapService.ConsumerElectric.testQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.testQResponse> testQAsync(sapService.ConsumerElectric.testQRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class stockBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cLABS_KField;
        
        private string cLABS_XField;
        
        private string cLABS_ZField;
        
        private string eKGRPField;
        
        private string lGORTField;
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CLABS_K {
            get {
                return this.cLABS_KField;
            }
            set {
                this.cLABS_KField = value;
                this.RaisePropertyChanged("CLABS_K");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLABS_X {
            get {
                return this.cLABS_XField;
            }
            set {
                this.cLABS_XField = value;
                this.RaisePropertyChanged("CLABS_X");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CLABS_Z {
            get {
                return this.cLABS_ZField;
            }
            set {
                this.cLABS_ZField = value;
                this.RaisePropertyChanged("CLABS_Z");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string EKGRP {
            get {
                return this.eKGRPField;
            }
            set {
                this.eKGRPField = value;
                this.RaisePropertyChanged("EKGRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LGORT {
            get {
                return this.lGORTField;
            }
            set {
                this.lGORTField = value;
                this.RaisePropertyChanged("LGORT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class queryModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string grpnoField;
        
        private string incodeField;
        
        private string storenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string grpno {
            get {
                return this.grpnoField;
            }
            set {
                this.grpnoField = value;
                this.RaisePropertyChanged("grpno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string incode {
            get {
                return this.incodeField;
            }
            set {
                this.incodeField = value;
                this.RaisePropertyChanged("incode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string storeno {
            get {
                return this.storenoField;
            }
            set {
                this.storenoField = value;
                this.RaisePropertyChanged("storeno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class shopToStore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shopidField;
        
        private string storenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shopid {
            get {
                return this.shopidField;
            }
            set {
                this.shopidField = value;
                this.RaisePropertyChanged("shopid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string storeno {
            get {
                return this.storenoField;
            }
            set {
                this.storenoField = value;
                this.RaisePropertyChanged("storeno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class shopBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shopidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shopid {
            get {
                return this.shopidField;
            }
            set {
                this.shopidField = value;
                this.RaisePropertyChanged("shopid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class chTranstype : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applynoField;
        
        private string mapField;
        
        private string pretransdateField;
        
        private string purcodeField;
        
        private string putrodernoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string applyno {
            get {
                return this.applynoField;
            }
            set {
                this.applynoField = value;
                this.RaisePropertyChanged("applyno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pretransdate {
            get {
                return this.pretransdateField;
            }
            set {
                this.pretransdateField = value;
                this.RaisePropertyChanged("pretransdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string purcode {
            get {
                return this.purcodeField;
            }
            set {
                this.purcodeField = value;
                this.RaisePropertyChanged("purcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string putroderno {
            get {
                return this.putrodernoField;
            }
            set {
                this.putrodernoField = value;
                this.RaisePropertyChanged("putroderno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class chTasnsdate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applynoField;
        
        private string pretransdateField;
        
        private string purcodeField;
        
        private string putrodernoField;
        
        private string remarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string applyno {
            get {
                return this.applynoField;
            }
            set {
                this.applynoField = value;
                this.RaisePropertyChanged("applyno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pretransdate {
            get {
                return this.pretransdateField;
            }
            set {
                this.pretransdateField = value;
                this.RaisePropertyChanged("pretransdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string purcode {
            get {
                return this.purcodeField;
            }
            set {
                this.purcodeField = value;
                this.RaisePropertyChanged("purcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string putroderno {
            get {
                return this.putrodernoField;
            }
            set {
                this.putrodernoField = value;
                this.RaisePropertyChanged("putroderno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class tsportBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string applynoField;
        
        private string custnoField;
        
        private string customerField;
        
        private string fnameField;
        
        private string fxxgrpField;
        
        private string hprcField;
        
        private string incodeField;
        
        private string mapField;
        
        private string operaterField;
        
        private string ordertypeField;
        
        private string outprdField;
        
        private string pflagField;
        
        private string pretransdateField;
        
        private string purcodeField;
        
        private string purtimeField;
        
        private string qtyField;
        
        private string remarkField;
        
        private string sgrpnoField;
        
        private string statField;
        
        private string storenoField;
        
        private string telField;
        
        private string unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string applyno {
            get {
                return this.applynoField;
            }
            set {
                this.applynoField = value;
                this.RaisePropertyChanged("applyno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string custno {
            get {
                return this.custnoField;
            }
            set {
                this.custnoField = value;
                this.RaisePropertyChanged("custno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
                this.RaisePropertyChanged("fname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fxxgrp {
            get {
                return this.fxxgrpField;
            }
            set {
                this.fxxgrpField = value;
                this.RaisePropertyChanged("fxxgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string hprc {
            get {
                return this.hprcField;
            }
            set {
                this.hprcField = value;
                this.RaisePropertyChanged("hprc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string incode {
            get {
                return this.incodeField;
            }
            set {
                this.incodeField = value;
                this.RaisePropertyChanged("incode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string operater {
            get {
                return this.operaterField;
            }
            set {
                this.operaterField = value;
                this.RaisePropertyChanged("operater");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ordertype {
            get {
                return this.ordertypeField;
            }
            set {
                this.ordertypeField = value;
                this.RaisePropertyChanged("ordertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string outprd {
            get {
                return this.outprdField;
            }
            set {
                this.outprdField = value;
                this.RaisePropertyChanged("outprd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string pflag {
            get {
                return this.pflagField;
            }
            set {
                this.pflagField = value;
                this.RaisePropertyChanged("pflag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string pretransdate {
            get {
                return this.pretransdateField;
            }
            set {
                this.pretransdateField = value;
                this.RaisePropertyChanged("pretransdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string purcode {
            get {
                return this.purcodeField;
            }
            set {
                this.purcodeField = value;
                this.RaisePropertyChanged("purcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string purtime {
            get {
                return this.purtimeField;
            }
            set {
                this.purtimeField = value;
                this.RaisePropertyChanged("purtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string sgrpno {
            get {
                return this.sgrpnoField;
            }
            set {
                this.sgrpnoField = value;
                this.RaisePropertyChanged("sgrpno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("stat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string storeno {
            get {
                return this.storenoField;
            }
            set {
                this.storenoField = value;
                this.RaisePropertyChanged("storeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class reTransBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string purcodeField;
        
        private string putordernoField;
        
        private string statField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string purcode {
            get {
                return this.purcodeField;
            }
            set {
                this.purcodeField = value;
                this.RaisePropertyChanged("purcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string putorderno {
            get {
                return this.putordernoField;
            }
            set {
                this.putordernoField = value;
                this.RaisePropertyChanged("putorderno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("stat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport/")]
    public partial class sportBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string applynoField;
        
        private string customerField;
        
        private string fxxgrpField;
        
        private string incodeField;
        
        private string installField;
        
        private string mapField;
        
        private string operaterField;
        
        private string ordertypeField;
        
        private string pflagField;
        
        private string pretransdateField;
        
        private string purcodeField;
        
        private string purtimeField;
        
        private string putordernoField;
        
        private double qtyField;
        
        private string remarkField;
        
        private string sgrpnoField;
        
        private string statField;
        
        private string storenoField;
        
        private string telField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string applyno {
            get {
                return this.applynoField;
            }
            set {
                this.applynoField = value;
                this.RaisePropertyChanged("applyno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fxxgrp {
            get {
                return this.fxxgrpField;
            }
            set {
                this.fxxgrpField = value;
                this.RaisePropertyChanged("fxxgrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string incode {
            get {
                return this.incodeField;
            }
            set {
                this.incodeField = value;
                this.RaisePropertyChanged("incode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string install {
            get {
                return this.installField;
            }
            set {
                this.installField = value;
                this.RaisePropertyChanged("install");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
                this.RaisePropertyChanged("map");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string operater {
            get {
                return this.operaterField;
            }
            set {
                this.operaterField = value;
                this.RaisePropertyChanged("operater");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ordertype {
            get {
                return this.ordertypeField;
            }
            set {
                this.ordertypeField = value;
                this.RaisePropertyChanged("ordertype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pflag {
            get {
                return this.pflagField;
            }
            set {
                this.pflagField = value;
                this.RaisePropertyChanged("pflag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string pretransdate {
            get {
                return this.pretransdateField;
            }
            set {
                this.pretransdateField = value;
                this.RaisePropertyChanged("pretransdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string purcode {
            get {
                return this.purcodeField;
            }
            set {
                this.purcodeField = value;
                this.RaisePropertyChanged("purcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string purtime {
            get {
                return this.purtimeField;
            }
            set {
                this.purtimeField = value;
                this.RaisePropertyChanged("purtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string putorderno {
            get {
                return this.putordernoField;
            }
            set {
                this.putordernoField = value;
                this.RaisePropertyChanged("putorderno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string sgrpno {
            get {
                return this.sgrpnoField;
            }
            set {
                this.sgrpnoField = value;
                this.RaisePropertyChanged("sgrpno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("stat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string storeno {
            get {
                return this.storenoField;
            }
            set {
                this.storenoField = value;
                this.RaisePropertyChanged("storeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStock", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class GetStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.stockBean arg0;
        
        public GetStockRequest() {
        }
        
        public GetStockRequest(sapService.ConsumerElectric.stockBean arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStockResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class GetStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.stockBean[] @return;
        
        public GetStockResponse() {
        }
        
        public GetStockResponse(sapService.ConsumerElectric.stockBean[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transport", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class transportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.sportBean arg0;
        
        public transportRequest() {
        }
        
        public transportRequest(sapService.ConsumerElectric.sportBean arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transportResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class transportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.reTransBean[] @return;
        
        public transportResponse() {
        }
        
        public transportResponse(sapService.ConsumerElectric.reTransBean[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="t_trans", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class t_transRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.tsportBean arg0;
        
        public t_transRequest() {
        }
        
        public t_transRequest(sapService.ConsumerElectric.tsportBean arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="t_transResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class t_transResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.reTransBean[] @return;
        
        public t_transResponse() {
        }
        
        public t_transResponse(sapService.ConsumerElectric.reTransBean[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ch_transdate", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class ch_transdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.chTasnsdate arg0;
        
        public ch_transdateRequest() {
        }
        
        public ch_transdateRequest(sapService.ConsumerElectric.chTasnsdate arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ch_transdateResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class ch_transdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.reTransBean[] @return;
        
        public ch_transdateResponse() {
        }
        
        public ch_transdateResponse(sapService.ConsumerElectric.reTransBean[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ch_transtype", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class ch_transtypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.chTranstype arg0;
        
        public ch_transtypeRequest() {
        }
        
        public ch_transtypeRequest(sapService.ConsumerElectric.chTranstype arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ch_transtypeResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class ch_transtypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.reTransBean[] @return;
        
        public ch_transtypeResponse() {
        }
        
        public ch_transtypeResponse(sapService.ConsumerElectric.reTransBean[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Getjdstoretoshop", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class GetjdstoretoshopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.shopBean arg0;
        
        public GetjdstoretoshopRequest() {
        }
        
        public GetjdstoretoshopRequest(sapService.ConsumerElectric.shopBean arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetjdstoretoshopResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class GetjdstoretoshopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.shopBean[] @return;
        
        public GetjdstoretoshopResponse() {
        }
        
        public GetjdstoretoshopResponse(sapService.ConsumerElectric.shopBean[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Getfxxtoshop", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class GetfxxtoshopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.shopToStore arg0;
        
        public GetfxxtoshopRequest() {
        }
        
        public GetfxxtoshopRequest(sapService.ConsumerElectric.shopToStore arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetfxxtoshopResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class GetfxxtoshopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public sapService.ConsumerElectric.shopToStore[] @return;
        
        public GetfxxtoshopResponse() {
        }
        
        public GetfxxtoshopResponse(sapService.ConsumerElectric.shopToStore[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class testRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public testRequest() {
        }
        
        public testRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public testResponse() {
        }
        
        public testResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testQ", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class testQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sapService.ConsumerElectric.queryModel arg0;
        
        public testQRequest() {
        }
        
        public testQRequest(sapService.ConsumerElectric.queryModel arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testQResponse", WrapperNamespace="http://transport/", IsWrapped=true)]
    public partial class testQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://transport/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public testQResponse() {
        }
        
        public testQResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDelegateChannel : sapService.ConsumerElectric.ServiceDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDelegateClient : System.ServiceModel.ClientBase<sapService.ConsumerElectric.ServiceDelegate>, sapService.ConsumerElectric.ServiceDelegate {
        
        public ServiceDelegateClient() {
        }
        
        public ServiceDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.GetStockResponse sapService.ConsumerElectric.ServiceDelegate.GetStock(sapService.ConsumerElectric.GetStockRequest request) {
            return base.Channel.GetStock(request);
        }
        
        public sapService.ConsumerElectric.stockBean[] GetStock(sapService.ConsumerElectric.stockBean arg0) {
            sapService.ConsumerElectric.GetStockRequest inValue = new sapService.ConsumerElectric.GetStockRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.GetStockResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).GetStock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.GetStockResponse> sapService.ConsumerElectric.ServiceDelegate.GetStockAsync(sapService.ConsumerElectric.GetStockRequest request) {
            return base.Channel.GetStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.GetStockResponse> GetStockAsync(sapService.ConsumerElectric.stockBean arg0) {
            sapService.ConsumerElectric.GetStockRequest inValue = new sapService.ConsumerElectric.GetStockRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).GetStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.transportResponse sapService.ConsumerElectric.ServiceDelegate.transport(sapService.ConsumerElectric.transportRequest request) {
            return base.Channel.transport(request);
        }
        
        public sapService.ConsumerElectric.reTransBean[] transport(sapService.ConsumerElectric.sportBean arg0) {
            sapService.ConsumerElectric.transportRequest inValue = new sapService.ConsumerElectric.transportRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.transportResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).transport(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.transportResponse> sapService.ConsumerElectric.ServiceDelegate.transportAsync(sapService.ConsumerElectric.transportRequest request) {
            return base.Channel.transportAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.transportResponse> transportAsync(sapService.ConsumerElectric.sportBean arg0) {
            sapService.ConsumerElectric.transportRequest inValue = new sapService.ConsumerElectric.transportRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).transportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.t_transResponse sapService.ConsumerElectric.ServiceDelegate.t_trans(sapService.ConsumerElectric.t_transRequest request) {
            return base.Channel.t_trans(request);
        }
        
        public sapService.ConsumerElectric.reTransBean[] t_trans(sapService.ConsumerElectric.tsportBean arg0) {
            sapService.ConsumerElectric.t_transRequest inValue = new sapService.ConsumerElectric.t_transRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.t_transResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).t_trans(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.t_transResponse> sapService.ConsumerElectric.ServiceDelegate.t_transAsync(sapService.ConsumerElectric.t_transRequest request) {
            return base.Channel.t_transAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.t_transResponse> t_transAsync(sapService.ConsumerElectric.tsportBean arg0) {
            sapService.ConsumerElectric.t_transRequest inValue = new sapService.ConsumerElectric.t_transRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).t_transAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.ch_transdateResponse sapService.ConsumerElectric.ServiceDelegate.ch_transdate(sapService.ConsumerElectric.ch_transdateRequest request) {
            return base.Channel.ch_transdate(request);
        }
        
        public sapService.ConsumerElectric.reTransBean[] ch_transdate(sapService.ConsumerElectric.chTasnsdate arg0) {
            sapService.ConsumerElectric.ch_transdateRequest inValue = new sapService.ConsumerElectric.ch_transdateRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.ch_transdateResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).ch_transdate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.ch_transdateResponse> sapService.ConsumerElectric.ServiceDelegate.ch_transdateAsync(sapService.ConsumerElectric.ch_transdateRequest request) {
            return base.Channel.ch_transdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.ch_transdateResponse> ch_transdateAsync(sapService.ConsumerElectric.chTasnsdate arg0) {
            sapService.ConsumerElectric.ch_transdateRequest inValue = new sapService.ConsumerElectric.ch_transdateRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).ch_transdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.ch_transtypeResponse sapService.ConsumerElectric.ServiceDelegate.ch_transtype(sapService.ConsumerElectric.ch_transtypeRequest request) {
            return base.Channel.ch_transtype(request);
        }
        
        public sapService.ConsumerElectric.reTransBean[] ch_transtype(sapService.ConsumerElectric.chTranstype arg0) {
            sapService.ConsumerElectric.ch_transtypeRequest inValue = new sapService.ConsumerElectric.ch_transtypeRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.ch_transtypeResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).ch_transtype(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.ch_transtypeResponse> sapService.ConsumerElectric.ServiceDelegate.ch_transtypeAsync(sapService.ConsumerElectric.ch_transtypeRequest request) {
            return base.Channel.ch_transtypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.ch_transtypeResponse> ch_transtypeAsync(sapService.ConsumerElectric.chTranstype arg0) {
            sapService.ConsumerElectric.ch_transtypeRequest inValue = new sapService.ConsumerElectric.ch_transtypeRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).ch_transtypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.GetjdstoretoshopResponse sapService.ConsumerElectric.ServiceDelegate.Getjdstoretoshop(sapService.ConsumerElectric.GetjdstoretoshopRequest request) {
            return base.Channel.Getjdstoretoshop(request);
        }
        
        public sapService.ConsumerElectric.shopBean[] Getjdstoretoshop(sapService.ConsumerElectric.shopBean arg0) {
            sapService.ConsumerElectric.GetjdstoretoshopRequest inValue = new sapService.ConsumerElectric.GetjdstoretoshopRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.GetjdstoretoshopResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).Getjdstoretoshop(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.GetjdstoretoshopResponse> sapService.ConsumerElectric.ServiceDelegate.GetjdstoretoshopAsync(sapService.ConsumerElectric.GetjdstoretoshopRequest request) {
            return base.Channel.GetjdstoretoshopAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.GetjdstoretoshopResponse> GetjdstoretoshopAsync(sapService.ConsumerElectric.shopBean arg0) {
            sapService.ConsumerElectric.GetjdstoretoshopRequest inValue = new sapService.ConsumerElectric.GetjdstoretoshopRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).GetjdstoretoshopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.GetfxxtoshopResponse sapService.ConsumerElectric.ServiceDelegate.Getfxxtoshop(sapService.ConsumerElectric.GetfxxtoshopRequest request) {
            return base.Channel.Getfxxtoshop(request);
        }
        
        public sapService.ConsumerElectric.shopToStore[] Getfxxtoshop(sapService.ConsumerElectric.shopToStore arg0) {
            sapService.ConsumerElectric.GetfxxtoshopRequest inValue = new sapService.ConsumerElectric.GetfxxtoshopRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.GetfxxtoshopResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).Getfxxtoshop(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.GetfxxtoshopResponse> sapService.ConsumerElectric.ServiceDelegate.GetfxxtoshopAsync(sapService.ConsumerElectric.GetfxxtoshopRequest request) {
            return base.Channel.GetfxxtoshopAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.GetfxxtoshopResponse> GetfxxtoshopAsync(sapService.ConsumerElectric.shopToStore arg0) {
            sapService.ConsumerElectric.GetfxxtoshopRequest inValue = new sapService.ConsumerElectric.GetfxxtoshopRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).GetfxxtoshopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.testResponse sapService.ConsumerElectric.ServiceDelegate.test(sapService.ConsumerElectric.testRequest request) {
            return base.Channel.test(request);
        }
        
        public string[] test(string arg0) {
            sapService.ConsumerElectric.testRequest inValue = new sapService.ConsumerElectric.testRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.testResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).test(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.testResponse> sapService.ConsumerElectric.ServiceDelegate.testAsync(sapService.ConsumerElectric.testRequest request) {
            return base.Channel.testAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.testResponse> testAsync(string arg0) {
            sapService.ConsumerElectric.testRequest inValue = new sapService.ConsumerElectric.testRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).testAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sapService.ConsumerElectric.testQResponse sapService.ConsumerElectric.ServiceDelegate.testQ(sapService.ConsumerElectric.testQRequest request) {
            return base.Channel.testQ(request);
        }
        
        public string[] testQ(sapService.ConsumerElectric.queryModel arg0) {
            sapService.ConsumerElectric.testQRequest inValue = new sapService.ConsumerElectric.testQRequest();
            inValue.arg0 = arg0;
            sapService.ConsumerElectric.testQResponse retVal = ((sapService.ConsumerElectric.ServiceDelegate)(this)).testQ(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sapService.ConsumerElectric.testQResponse> sapService.ConsumerElectric.ServiceDelegate.testQAsync(sapService.ConsumerElectric.testQRequest request) {
            return base.Channel.testQAsync(request);
        }
        
        public System.Threading.Tasks.Task<sapService.ConsumerElectric.testQResponse> testQAsync(sapService.ConsumerElectric.queryModel arg0) {
            sapService.ConsumerElectric.testQRequest inValue = new sapService.ConsumerElectric.testQRequest();
            inValue.arg0 = arg0;
            return ((sapService.ConsumerElectric.ServiceDelegate)(this)).testQAsync(inValue);
        }
    }
}
